name: Mesh SDK Usage Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  search-mesh-usage:
    runs-on: ubuntu-latest
    steps:
      - name: Search for Mesh SDK Usage
        run: |
          curl -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               "https://api.github.com/search/code?q=%22%40meshsdk/core%22+in:file+filename:package.json+filename:yarn.lock" \
               | jq '{total_count: .total_count, incomplete_results: .incomplete_results}'
