name: Update Discord Stats

on:
  schedule:
    - cron: '0 2 1 * *'      # at 02:00 UTC on the 1st of every month
  workflow_dispatch:         # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install discord.js

      - name: Run stats script
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GUILD_ID:       ${{ secrets.GUILD_ID }}
        run: node scripts/discord-stats/getStats.js

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Commit changes
        run: |
          git add .
          git commit -m "chore: monthly Discord stats" || echo "No changes to commit"
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
