name: Update Discord Stats
on:
  schedule:
    - cron: '0 2 1 * *'
  workflow_dispatch:

permissions:
  contents: write      # allow GITHUB_TOKEN to push

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Discord Stats Script
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_ANALYTICS_TOKEN }}
          BACKFILL: 'false'
          BACKFILL_YEAR: '2025'
        run: node scripts/discord-stats/getStats.js

      - name: Commit stats.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mesh-gov-updates/discord-stats/stats.json
          git commit -m "chore: monthly Discord stats" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
