name: Update Discord Stats
on:
  schedule:
    - cron: '0 2 1 * *'
  workflow_dispatch:

permissions:
  contents: write      # allow GITHUB_TOKEN to push

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Discord-Stats Action
        uses: Signius/discord-stats-action@1.0.1
        with:
          discord-token: ${{ secrets.DISCORD_TOKEN }}
          guild-id:       ${{ secrets.GUILD_ID }}
          output-file:    mesh-gov-updates/discord-stats/stats.json
          backfill:       'false'
          backfill-year:  '2025'

      - name: Commit stats.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mesh-gov-updates/discord-stats/stats.json
          git commit -m "chore: monthly Discord stats" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
